name: NPM - Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: write-all

env:
  CI: false
  Branches: master
  MainBranch: master
  NPMRegistry: https://registry.npmjs.org/
  InstallCommand: npm ci
  DeployCommand: npm publish --access public
  Organization: powhound4
  Repository: Crystal-shop-old
  Output: _site
